### ISSUE TITLE
install_supersonic.sh does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/supersonic#12]
```
Apparently, there is a missing call to "autogen.sh" inside 
"install_supersonic.sh" script.

Pushed trivial fix into a separate branch in my clone - 
https://code.google.com/r/wojtekzozlak-supersonic/source/detail?r=6587b3edc9dba6
1ad8f4ebb9551f4744e25b5af8&name=installation-fix .
```

Original issue reported on code.google.com by `wojtekzo...@gmail.com` on 25 Jan 2014 at 6:17

**Comment by mtanski** [comment]
I think this ticket should be closed. I don't know why it got migrated with the import. Esp. since there is a comment from one of the authors describing proper usage (as not to run into the issue).

**Comment by ptabor** [comment]
I'm sorry about extremely long delay. After Google Code shutdown I didn't recovered my presence on github till now.
