### ISSUE TITLE
possible speedup by using an SIMD popcount

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/supersonic#4]
```
The gcc builtin uses a lookup table but it is possible to do better.

http://gcc.gnu.org/bugzilla/show_bug.cgi?id=36041 - existing gcc bug for 
improving the builtin popcount. 

https://groups.google.com/group/comp.arch/msg/ba28c5dbd47a3bba?dmode=source&outp
ut=gplain&noredirect&pli=1 - this post by Terje Mathisen describes the technique
```

Original issue reported on code.google.com by `dbremner@gmail.com` on 17 Oct 2012 at 2:02

**Comment by mtanski** [comment]
This should probably be closed as it's an old ticket from google code and I believe current version of gcc (with the right minimum target arch) will use the builtin popcount instruction.

Source: We use it in our code for compressed bitmap indexes.
